

name: Gh-Runner setup


on:
  push: 
  workflow_dispatch:
    inputs:
      runner_group:
        required: true
        type: string

jobs:
  clean_workdirs:
    timeout-minutes: 10
    name: cleanup
    runs-on: ubuntu-latest
    steps:
    - name: Ubuntu
      if: ${{ inputs.runner_group == 'ubuntu-latest' }} 
      run: echo 'ubuntu'
    - name: Centos
      if: ${{ inputs.runner_group != 'ubuntu-latest' }} 
      run: echo 'centos'
