

name: Gh-Runner setup


on: [push]

jobs:
  clean_workdirs:
    timeout-minutes: 10
    name: cleanup
    runs-on: ubuntu-latest
    steps:
    - name: echo ${{ vars.PRADEEP }}
      run: echo ${{ vars.PRADEEP }}
    - name: hello
      run: echo hello
    - name: Print statement
      run: echo ${{ env.PRADEEP }}
